server:
  port: 8082

spring:
 datasource:
    url: jdbc:postgresql://ep-summer-rice-aot33kkd.c-2.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_y7FnzQkq8rAW
    driver-class-name: org.postgresql.Driver
 jackson:
    date-format: yyyy-MM-dd
# 七牛云配置
qiniu:
  access-key: PWMsSGLWdeomLovWAThPNWmGVbpH3-ynemrRJb54
  secret-key: BpL3U6BaH0jC3js1ac28knwGewlEmdM2TTYgFJYW
  bucket-name: bookwws
  domain: http://tikyxorg9.hb-bkt.clouddn.com  # 绑定的访问域名
  pdf-folder: pdf/
  cover-folder: cover/

  # thymeleaf缓存关闭，开发实时刷新
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8

# MyBatis-Plus
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.demo
  configuration:
    map-underscore-to-camel-case: true

